site_name: 小組查經帶領訓練
site_url: https://cbcgb-com.github.io/sgbs-training/

theme:
  name: "shadcn"
  custom_dir: "docs/templates"

nav:
  - 主頁: index.md
  - 課堂講義:
      - 課堂（一）查經的意義和裝備: class-notes/lesson-1-foundations.md
      - 課堂（二）分析敘述文: class-notes/lesson-2-narrative.md
      - 課堂（三）提問題的技術: class-notes/lesson-3-questioning.md
      - 課堂（四）分析論說文: class-notes/lesson-4-argumentation.md
      - 課堂（五）應對臨場狀況: class-notes/lesson-5-situations.md
  - 工具:
      - 論說⽂體的歸納法查經: tools/ibs-argumentation-notes.md
      - 敘述⽂體的歸納法查經: tools/ibs-narrative-notes.md
  - 範例:
      - 路加福音筆記: examples/luke-study-notes.md
      - 路加福音中的文學手法: examples/luke-literary-devices.md
      - 羅馬書查經筆記範例: examples/romans-study-notes.md
  - 資源:
      - 查經筆記指南: resources/bible-study-notes.md
      - 線上查經注意事項: resources/virtual-study.md
      - 提問題的模板: resources/questions.md
      - 設計查經主題: resources/theme.md
      - 聖經參考書: resources/books.md
      - 課堂錄音: resources/recordings.md
      - 更多神學裝備: resources/theology-equipments.md
      - 對於生成式AI的反思: resources/genai.md

extra_css:
  - stylesheets/extra.css
  - stylesheets/transition.css

extra_javascript:
  - javascripts/expandable-cards.js
  - javascripts/chinese-toggle.js

plugins:
  - search

# Taken from here: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.blocks.details
  - pymdownx.superfences
  - markdown.extensions.attr_list
  - pymdownx.tabbed

repo_name: "cbcgb-com/sgbs-training"
repo_url: "https://github.com/cbcgb-com/sgbs-training"
